### ISSUE TITLE
Public Key Transmission

### ISSUE THREAD

**Issue by Romulus10** [fennelLabs/Fennel-Protocol#28]
We will develop a Substrate module that contains public key management extrinsics for broadcasting public keys' existence and locations as a signal.

**Comment by PhillyWebGuy** [comment]
@Romulus10 And by "broadcasting public keys' existence," I'm guessing that is broadcasting an event to the chain. Also, what arguments would this take? And do we have examples of other signals?

**Comment by Romulus10** [comment]
Yeah you'll use an extrinsic here to submit a public key to storage and emit an Event. The arguments will be the fingerprint of the key and the location the key is stored at in public storage.
