### ISSUE TITLE
Whiteflag Reference Codes 1, 2, and 4.

### ISSUE THREAD

**Issue by Romulus10** [fennelLabs/Fennel-Protocol#35]
We will create a Minimum Implementation of Whiteflag, fully resident as a component of Fennel Protocol, which will support operations for creating, recalling, updating, and discontinuing Whiteflag signals.

**Comment by PhillyWebGuy** [comment]
What reference materials are you looking at to do this work? I ask because I'm thinking to myself if I had to do this work, where would I start? I'm looking to start understanding your thought process when it comes to the implementation tasks you are working on.

**Comment by Romulus10** [comment]
This particular task will refer to the Whiteflag Protocol specification (which I planned on attaching later tonight, just didn't get there yet). Other tasks pull directly from either the specification I wrote for Fennel Protocol and from conversation occurring here and on Discord.
