### ISSUE TITLE
Identity Signature

### ISSUE THREAD

**Issue by Romulus10** [fennelLabs/Fennel-Protocol#4]
The Identity module will be updated with an extrinsic set that will allow for an identity to issue signed certificates and sign existing certificates.

**Comment by Romulus10** [comment]
Alright. So this'll need a way to just embed arbitrary data on-chain with an identity tagged. The signature can just be the signature that happens when the transaction is submitted. Does that make sense?

**Comment by isaacadams** [comment]
> the signature that happens when the transaction is submitted

meaning the transaction hash?

> embed arbitrary data on-chain with an identity tagged

sounds good. any limits on the data they are allowed to input?

**Comment by Romulus10** [comment]
> > the signature that happens when the transaction is submitted
> 
> meaning the transaction hash?
The cryptographic signature applied to the transaction, not the hash.

> > embed arbitrary data on-chain with an identity tagged
> 
> sounds good. any limits on the data they are allowed to input?
That's what I'm considering. Length should definitely be limited, I think, and it should probably be u16 to open up room for unicode characters.

**Comment by isaacadams** [comment]
> The cryptographic signature applied to the transaction, not the hash.

ah, of course. I see now -- thanks for clearing that up!

> That's what I'm considering. Length should definitely be limited, I think, and it should probably be u16 to open up room for unicode characters.

sounds about right to me. let me know if you want me to dive into some research for this. Otherwise, this sounds like a plan.

**Comment by Romulus10** [comment]
I think we'll be able to play with the parameters during testing and make sure they make sense. That should work out.
