### ISSUE TITLE
Set Up Public Testnet

### ISSUE THREAD

**Issue by Romulus10** [fennelLabs/Fennel-Protocol#45]

**Comment by PhillyWebGuy** [comment]
Is something that would live on a cloud provider's hardware?

**Comment by Romulus10** [comment]
I believe it would probably have to.

**Comment by PhillyWebGuy** [comment]
Do you have an account already and/or preference with a cloud provider? And what constitutes a testnet? More than one node operating?

**Comment by Romulus10** [comment]
We currently have neither an account nor a preference for a cloud provider. We need to keep costs fairly low, though. And basically, yes. You need enough to create a meaningful microcosm of what the network consensus process would look like at scale.

**Comment by PhillyWebGuy** [comment]
<img width="1160" alt="Screen Shot 2022-01-12 at 8 39 39 PM" src="https://user-images.githubusercontent.com/449963/149250659-b210dff0-006c-44dc-9f4e-b4fed63d3261.png">

**Comment by PhillyWebGuy** [comment]
<img width="1162" alt="Screen Shot 2022-01-12 at 8 39 47 PM" src="https://user-images.githubusercontent.com/449963/149250675-e8ed2ffa-ac45-444a-b573-120ce459af4f.png">

**Comment by PhillyWebGuy** [comment]
<img width="1161" alt="Screen Shot 2022-01-12 at 8 39 56 PM" src="https://user-images.githubusercontent.com/449963/149250686-b84f2f2b-632d-4fa6-bfaa-ddedf9a89023.png">

**Comment by PhillyWebGuy** [comment]
The quickest and cheapest way to do this:

1) Set up an AWS and get a bunch of free credits
2) Spin up a VPC with two different public subnets
3) Manually deploy an EC2 instance to each subnet
4) Manually build and run a node in each subnet
5) Document it

**Comment by PhillyWebGuy** [comment]
The above, of course, is an AWS "estimate" but realistically this should be do-able for < $50/month and you can pretty easily set up alerts if something odd happens with cost/utilization.

**Comment by Romulus10** [comment]
Yeah this looks like a really solid option for when we get there.

**Comment by PhillyWebGuy** [comment]
Well, lemme know when you want to set this up. I can probably get it rolling in maybe two nights.

**Comment by Romulus10** [comment]
This is currently scheduled for Milestone 3, which will mostly take place during March.

**Comment by Romulus10** [comment]
This solves a TON of the planning we need to do though.
